/**
 * [Claude-authored file]
 * Created: 2026-04-05 | Model: claude-4.6-opus-high-thinking
 * Task: Test DreamTask action links (preserve/complete/remove) and subsequent load interpretation
 * Prompt summary: "test that clicking 3 action links modifies note content; verify subsequent load interprets designations"
 */
import { jest } from "@jest/globals";
import { completeDreamTask, updateDreamTaskTaskMetadata } from "../lib/dashboard/dream-task-internals.js";
import { analyzeDreamTasks } from "../lib/dream-task-service.js";
import { SETTING_KEYS } from "../lib/constants/settings.js";
import { replaceSectionContent } from "../lib/util/replace-note-section-content.js";
import { SAMPLE_TASKS } from "./fixtures/tasks.js";

const MOCK_NOTE_UUID = "dream-note-uuid";

const MOCK_NOTE_CONTENT = `## Sunday April 5, 2026

**Your goals this quarter/month/week:**
Focus on launching Task Agent Pro and building daily outreach habits.

### 1. Message one luminary or press (Rating: 9/10)
<!-- task:task-2 -->
<!-- suggestion:sug-100 -->
This task aligns with your daily outreach goal and press outreach objective.

### 2. Update budget (Rating: 7/10)
<!-- task:task-7 -->
<!-- suggestion:sug-101 -->
Financial review supports your quarterly planning goals.

### 3. Build a landing page for Task Agent Pro (Rating: 8/10)
<!-- suggestion:sug-102 -->
An invented task aligned with your product launch goal.

---

> Generated by Anthropic Claude · claude-sonnet-4-6
`;

// ----------------------------------------------------------------------------------------------
// @desc Build a mock app whose dream note content updates when replaceNoteContent is called.
// [Claude claude-4.6-opus-high-thinking] Task: mock app with section-aware replaceNoteContent
// Prompt: "test that clicking 3 action links modifies note content"
function buildMockAppWithNote(initialContent) {
  let noteContent = initialContent;

  const app = {
    settings: {
      [SETTING_KEYS.TASK_DOMAINS]: JSON.stringify({ selectedDomainUuid: "dom-work" }),
    },
    createNote: jest.fn().mockResolvedValue(MOCK_NOTE_UUID),
    filterNotes: jest.fn().mockResolvedValue([]),
    findNote: jest.fn().mockImplementation(({ uuid, name }) => {
      if (uuid === MOCK_NOTE_UUID || name) return Promise.resolve({ uuid: MOCK_NOTE_UUID });
      return Promise.resolve(null);
    }),
    getNoteContent: jest.fn().mockImplementation(({ uuid }) => {
      if (uuid === MOCK_NOTE_UUID) return Promise.resolve(noteContent);
      return Promise.resolve("");
    }),
    getTaskDomains: jest.fn().mockResolvedValue([{ uuid: "dom-work", name: "Work" }]),
    getTaskDomainTasks: jest.fn().mockResolvedValue(SAMPLE_TASKS),
    replaceNoteContent: jest.fn().mockImplementation((_handle, content, options) => {
      noteContent = replaceSectionContent(noteContent, content, options);
      return Promise.resolve(true);
    }),
    insertNoteContent: jest.fn().mockResolvedValue(undefined),
    updateTask: jest.fn().mockResolvedValue(true),
    currentNoteContent: () => noteContent,
  };

  return app;
}

// [Claude claude-4.6-opus-high-thinking] Generated tests for: DreamTask action links and subsequent load
describe("DreamTask action links", () => {
  afterEach(() => {
    jest.useRealTimers();
  });

  describe("clicking action links modifies the dream task content note", () => {
    it("preserve action inserts dream-preserve:through-tomorrow comment into the note", async () => {
      const app = buildMockAppWithNote(MOCK_NOTE_CONTENT);
      const task = { suggestionId: "sug-100", title: "Message one luminary or press", uuid: "task-2", rating: 9 };

      const result = await updateDreamTaskTaskMetadata(app, MOCK_NOTE_UUID, task, { preserveThroughTomorrow: true });

      expect(result).toBe(true);
      expect(app.replaceNoteContent).toHaveBeenCalledTimes(1);
      const updatedBody = app.replaceNoteContent.mock.calls[0][1];
      expect(updatedBody).toContain("<!-- dream-preserve:through-tomorrow -->");
      expect(updatedBody).not.toContain("<!-- dream-completed-at:");
      expect(updatedBody).not.toContain("<!-- dream-removed-at:");
    });

    it("complete action inserts dream-completed-at timestamp comment into the note", async () => {
      const app = buildMockAppWithNote(MOCK_NOTE_CONTENT);
      const task = { suggestionId: "sug-101", title: "Update budget", uuid: "task-7", rating: 7 };
      const completedAt = "2026-04-05T14:30:00.000Z";

      const result = await updateDreamTaskTaskMetadata(app, MOCK_NOTE_UUID, task, { completedAt, removedAt: null });

      expect(result).toBe(true);
      expect(app.replaceNoteContent).toHaveBeenCalledTimes(1);
      const updatedBody = app.replaceNoteContent.mock.calls[0][1];
      expect(updatedBody).toContain(`<!-- dream-completed-at:${ completedAt } -->`);
      expect(updatedBody).not.toContain("<!-- dream-removed-at:");
    });

    it("remove action inserts dream-removed-at timestamp comment into the note", async () => {
      const app = buildMockAppWithNote(MOCK_NOTE_CONTENT);
      const task = { suggestionId: "sug-102", title: "Build a landing page for Task Agent Pro", rating: 8 };
      const removedAt = "2026-04-05T15:00:00.000Z";

      const result = await updateDreamTaskTaskMetadata(app, MOCK_NOTE_UUID, task, { completedAt: null, removedAt });

      expect(result).toBe(true);
      expect(app.replaceNoteContent).toHaveBeenCalledTimes(1);
      const updatedBody = app.replaceNoteContent.mock.calls[0][1];
      expect(updatedBody).toContain(`<!-- dream-removed-at:${ removedAt } -->`);
      expect(updatedBody).not.toContain("<!-- dream-completed-at:");
    });

    it("toggling preserve off removes the dream-preserve comment from the note", async () => {
      const preservedContent = MOCK_NOTE_CONTENT.replace(
        "<!-- suggestion:sug-100 -->\n",
        "<!-- suggestion:sug-100 -->\n<!-- dream-preserve:through-tomorrow -->\n",
      );
      const app = buildMockAppWithNote(preservedContent);
      const task = { suggestionId: "sug-100", title: "Message one luminary or press", uuid: "task-2", rating: 9 };

      const result = await updateDreamTaskTaskMetadata(app, MOCK_NOTE_UUID, task, { preserveThroughTomorrow: false });

      expect(result).toBe(true);
      const updatedBody = app.replaceNoteContent.mock.calls[0][1];
      expect(updatedBody).not.toContain("<!-- dream-preserve:through-tomorrow -->");
    });
  });

  describe("completing DreamTask suggestions updates Amplenote tasks", () => {
    it("complete action calls app.updateTask for an existing task", async () => {
      jest.useFakeTimers().setSystemTime(new Date("2026-04-29T22:30:00Z"));
      const app = buildMockAppWithNote(MOCK_NOTE_CONTENT);
      const task = { isExisting: true, suggestionId: "sug-101", title: "Update budget", uuid: "task-7", rating: 7 };

      const result = await completeDreamTask(app, MOCK_NOTE_UUID, task);

      expect(result).toBe(true);
      expect(app.updateTask).toHaveBeenCalledWith("task-7", { completedAt: 1777501800 });
      expect(app.insertNoteContent).not.toHaveBeenCalled();
      const updatedBody = app.replaceNoteContent.mock.calls[0][1];
      expect(updatedBody).toContain("<!-- dream-completed-at:1777501800 -->");
    });

    it("complete action creates today's daily jot and inserts a completed task when the task is new", async () => {
      jest.useFakeTimers().setSystemTime(new Date("2026-04-29T22:30:00Z"));
      const app = buildMockAppWithNote(MOCK_NOTE_CONTENT);
      app.findNote.mockImplementation(({ name, uuid }) => {
        if (uuid === MOCK_NOTE_UUID) return Promise.resolve({ uuid: MOCK_NOTE_UUID });
        if (name === "April 29th, 2026") return Promise.resolve(null);
        if (name) return Promise.resolve({ uuid: MOCK_NOTE_UUID });
        return Promise.resolve(null);
      });
      app.createNote.mockResolvedValue("daily-jot-uuid");
      const task = { isExisting: false, suggestionId: "sug-102", title: "Build a landing page for Task Agent Pro", rating: 8 };

      const result = await completeDreamTask(app, MOCK_NOTE_UUID, task);

      expect(result).toBe(true);
      expect(app.findNote).toHaveBeenCalledWith({ name: "April 29th, 2026", tags: ["daily-jots"] });
      expect(app.createNote).toHaveBeenCalledWith("April 29th, 2026", ["daily-jots"]);
      expect(app.insertNoteContent).toHaveBeenCalledWith(
        { uuid: "daily-jot-uuid" },
        "\n- [x] Build a landing page for Task Agent Pro <!-- {\"completedAt\":1777501800} -->\n",
        { atEnd: true },
      );
      expect(app.updateTask).not.toHaveBeenCalled();
      const updatedBody = app.replaceNoteContent.mock.calls[0][1];
      expect(updatedBody).toContain("<!-- dream-completed-at:1777501800 -->");
    });
  });

  describe("subsequent load interprets previously activated designations", () => {
    it("completed task is hidden, removed task is hidden, preserved task remains visible", async () => {
      const app = buildMockAppWithNote(MOCK_NOTE_CONTENT);
      const preserveTask = { suggestionId: "sug-100", title: "Message one luminary or press", uuid: "task-2", rating: 9 };
      const completeTask = { suggestionId: "sug-101", title: "Update budget", uuid: "task-7", rating: 7 };
      const removeTask = { suggestionId: "sug-102", title: "Build a landing page for Task Agent Pro", rating: 8 };

      await updateDreamTaskTaskMetadata(app, MOCK_NOTE_UUID, preserveTask, { preserveThroughTomorrow: true });
      await updateDreamTaskTaskMetadata(app, MOCK_NOTE_UUID, completeTask,
        { completedAt: "2026-04-05T14:30:00.000Z", removedAt: null });
      await updateDreamTaskTaskMetadata(app, MOCK_NOTE_UUID, removeTask,
        { completedAt: null, removedAt: "2026-04-05T15:00:00.000Z" });

      const todayLabel = new Date().toLocaleString([], { year: "numeric", month: "long", day: "numeric" });
      const noteName = `Dashboard proposed tasks for ${ todayLabel }`;
      const result = await analyzeDreamTasks(app, { noteName, minimumTaskCount: 1, forceRefresh: false });

      expect(result.cached).toBe(true);
      expect(result.tasks.length).toBe(1);

      const remainingTask = result.tasks[0];
      expect(remainingTask.title).toBe("Message one luminary or press");
      expect(remainingTask.preserveThroughTomorrow).toBe(true);
      expect(remainingTask.completedAt).toBeFalsy();
      expect(remainingTask.removedAt).toBeFalsy();
    });

    it("all three tasks remain visible when none have been dismissed", async () => {
      const app = buildMockAppWithNote(MOCK_NOTE_CONTENT);
      const todayLabel = new Date().toLocaleString([], { year: "numeric", month: "long", day: "numeric" });
      const noteName = `Dashboard proposed tasks for ${ todayLabel }`;
      const result = await analyzeDreamTasks(app, { noteName, minimumTaskCount: 1, forceRefresh: false });

      expect(result.cached).toBe(true);
      expect(result.tasks.length).toBe(3);
    });
  });
});
