// [OpenAI GPT-6-authored file]
// Created: 2026-09-05
// Task: Exercise host dependency enforcement against real esbuild graphs, including tree-shaken imports.
import { execFileSync } from "node:child_process";
import { assertHostPluginBoundary } from "../host-plugin-boundary.js";

// ----------------------------------------------------------------------------------------------
// @desc Build a small host entry in Node so esbuild runs outside Jest's jsdom environment.
// @param {string} contents - Source of the fixture entry point.
// @param {object} options - Optional packages mode and source filename.
// @returns {object} Actual esbuild metadata for the fixture's full dependency graph.
// [OpenAI GPT-6] Use real dependency resolution and tree shaking instead of fabricated metadata.
function buildHostMetadata(contents, { packages = "external", sourcefile = "host-fixture.js" } = {}) {
  const buildScript = `
    import esbuild from "esbuild";
    import path from "node:path";
    import { createLibImportsPlugin } from "./lib-imports-plugin.js";
    const options = JSON.parse(process.argv[1]);
    const result = await esbuild.build({
      bundle: true, format: "iife", metafile: true, packages: options.packages === "external" ? "external" : undefined,
      plugins: [createLibImportsPlugin(path.resolve("lib"))],
      stdin: { contents: options.contents, loader: "jsx", resolveDir: process.cwd(), sourcefile: options.sourcefile },
      write: false,
    });
    process.stdout.write(JSON.stringify(result.metafile));
  `;
  const output = execFileSync(process.execPath, ["--input-type=module", "-e", buildScript,
    JSON.stringify({ contents, packages, sourcefile })], { encoding: "utf8" });
  return JSON.parse(output);
}

// ----------------------------------------------------------------------------------------------
// @desc Allow shared calendar utilities that have no React dependencies.
// [OpenAI GPT-6] Confirm valid sharing remains supported by the host build.
test("accepts a React-free shared utility", () => {
  const metadata = buildHostMetadata('import { normalizeExternalCalendarEvents } from "util/calendar-utility"; '
    + 'globalThis.normalizeEvents = normalizeExternalCalendarEvents;');
  expect(() => assertHostPluginBoundary(metadata)).not.toThrow();
});

// ----------------------------------------------------------------------------------------------
// @desc Catch a hook dependency even when the generated output has no external runtime imports.
// [OpenAI GPT-6] Bundling packages removes external imports but must not conceal the hook dependency.
test("rejects a hook dependency without external runtime imports", () => {
  const metadata = buildHostMetadata('import useExternalCalendarEvents from "hooks/use-external-calendar-events"; '
    + 'globalThis.hostValue = 1;', { packages: "bundle" });
  const outputImports = Object.values(metadata.outputs).flatMap(output => output.imports);
  expect(outputImports).toEqual([]);
  expect(() => assertHostPluginBoundary(metadata)).toThrow("lib/hooks/use-external-calendar-events.js");
});

// ----------------------------------------------------------------------------------------------
// @desc Reject a hook source even when all its code is eliminated from the output.
// [OpenAI GPT-6] The boundary applies to inputs, regardless of their contribution to generated bytes.
test("rejects a fully tree-shaken hook source", () => {
  const sourcefile = "lib/hooks/use-unused-value.js";
  const metadata = buildHostMetadata("const unusedValue = 1;", { sourcefile });
  const outputBytes = Object.values(metadata.outputs).reduce((total, output) => total + (output.inputs[sourcefile]?.bytesInOutput || 0), 0);
  expect(outputBytes).toBe(0);
  expect(() => assertHostPluginBoundary(metadata)).toThrow(sourcefile);
});

// ----------------------------------------------------------------------------------------------
// @desc Reject component source files even if they currently export only ordinary JavaScript.
// [OpenAI GPT-6] A plain export must be moved out of the component before the host can share it.
test("rejects a JSX module without React imports", () => {
  const metadata = buildHostMetadata("globalThis.hostValue = 1;", { sourcefile: "lib/dashboard/example-component.jsx" });
  expect(() => assertHostPluginBoundary(metadata)).toThrow("example-component.jsx");
});

// ----------------------------------------------------------------------------------------------
// @desc Prevent bypassing the boundary by bundling React instead of externalizing it.
// [OpenAI GPT-6] Both the normal external package policy and a bundled React dependency must fail.
test.each(["bundle", "external"])("rejects React with packages=%s", packages => {
  const metadata = buildHostMetadata('import React from "react"; globalThis.hostValue = React;', { packages });
  expect(() => assertHostPluginBoundary(metadata)).toThrow(/react/);
});

// ----------------------------------------------------------------------------------------------
// @desc Preserve the ban on other external runtime dependencies in the host plugin.
// [OpenAI GPT-6] The host has no module loader for any external package.
test("rejects external packages with the importer named in the error", () => {
  const metadata = buildHostMetadata('import marked from "marked"; globalThis.hostValue = marked;');
  expect(() => assertHostPluginBoundary(metadata)).toThrow("host-fixture.js imports marked");
});
